<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MediatR" Version="14.1.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Guessy.Domain\Guessy.Domain.csproj"/>
        <ProjectReference Include="..\Guessy.Infrastructure\Guessy.Infrastructure.csproj"/>
    </ItemGroup>

</Project>
